* Aquaris - My NixOS module library
Use Aquaris to easily manage related machines, their users and secrets!

** Quickstart
Check out the [[file:docs/quickstart.org][quickstart]] guide and the provided [[file:example][example]] configuration!

** Declarative filesystem configuration
Inspired by [[https://github.com/nix-community/disko][disko]], but dissatisfied with its verbosity,
suboptimal integration and some edge-case bugs,
Aquaris implements a fairly complete filesystem configuration library.

It supports regular filesystems, btrfs subvolumes, swap,
LUKS-encrypted partitions and even complex filesystems like
LVM Volume Groups & Logical Volumes
and ZFS pools and datasets.

With very compact semantics, provided default options
and deep integration into the rest of Aquaris's modules,
most disko users should find this library a worthy replacement
for [[https://github.com/nix-community/disko/blob/276a0d055a720691912c6a34abb724e395c8e38a/example/swap.nix][dozens]] of [[https://github.com/nix-community/disko/blob/276a0d055a720691912c6a34abb724e395c8e38a/example/luks-btrfs-subvolumes.nix][lines]] of [[https://github.com/nix-community/disko/blob/276a0d055a720691912c6a34abb724e395c8e38a/example/zfs.nix][code]]!

** Secrets management
Aquaris uses [[https://github.com/42LoCo42/sillysecrets][sillysecrets]] for powerful group-based secret management.
Every group can become an encryption target (by specifying a public key)
and can also contain the secrets of other groups
or grant them access to their own.

** Image-less containers
Want to run services in =virtualisation.oci-containers= for security reasons,
but all those huge Docker images eat your disk space, require manual updates
and provide attackers with useful shell utils or, worst of all, root access,
just because upstream couldn't be bothered to make them work rootless?

Just use Nix packages! Aquaris includes [[file:docs/module/pnoc.org][PNOC]], the module for Pure NixOS Containers,
which simply bind-mounts service closures from your host's Nix store into empty containers.
It also runs every container under its own service account
and optinally integrates with the secrets management facility
if secrets should be provided as files in a container.

** Documentation
- [[file:docs/lib.org][Standard library]]
- Modules:
  - [[file:docs/module/caches.org][Binary caches]]
  - [[file:docs/module/dnscrypt.org][Local dnscrypt proxy]]
  - [[file:docs/module/filesystems.org][Filesystems]]
  - [[file:docs/module/home/main.org][home-manager settings]]
  - [[file:docs/module/lanzaboote.org][Secure Boot using Lanzaboote]]
  - [[file:docs/module/machine.org][General machine settings]]
  - [[file:docs/module/persist.org][root-on-tmpfs and persistency]]
  - [[file:docs/module/pnoc.org][Container management]]
  - [[file:docs/module/secrets.org][Secrets management]]
  - [[file:docs/module/users.org][User management]]

** TODOs
Check out the [[file:todo/TODO.org][TODO file]]!
