* home-manager modules of Aquaris
All of these modules are rooted in =home-manager.users.<username>.aquaris=
and are enabled by default unless otherwise mentioned.

** [[file:../../module/home/bat.nix][bat]]
Enable [[https://github.com/sharkdp/bat][bat]] for manpage rendering

** [[file:../../module/home/direnv.nix][direnv]]
Enable [[https://github.com/direnv/direnv][direnv]] and [[https://github.com/nix-community/nix-direnv][nix-direnv]] integration

** [[file:../../module/home/emacs/default.nix][emacs]]
Declarative [[https://www.gnu.org/software/emacs/][Emacs]] configuration management

*** Options
- =enable= (boolean): Enable the Emacs configuration.
  Default: false

- =package=: Which Emacs package to use.
  Default: =pkgs.emacs29=

- =startupTimer= (boolean): Enable the startup timer.
  Default: true

- =usePackage=:
  - =alwaysDefer= (boolean): Always defer loading of packages.
    Default: false

  - =statistics= (boolean): Gather statistics about package loading times.
    Default: false

  - =verbose= (boolean): Log all loaded packages.
    Default: false

- =prelude= (string): Config to add before loading packages
  Default: empty

- =postlude= (string): Config to add after loading packages
  Default: empty

- =config=: Set of Emacs package configurations.
  Options: every keyword from [[https://github.com/jwiegley/use-package][use-package]]
  (except =disabled= and =pin=; =bind*= is set as =bind'=) and:
  - =package=: Explicit package name or function taking =epkgs=
    Default: entry name

  - =extraPackages= (list of package):
    Extra packages required by this Emacs package.
    They will be added to =home.packages=. Default: empty list

** [[file:../../module/home/eza.nix][eza]]
Enable eza, a replacement for ls

** [[file:../../module/home/firefox.nix][firefox]]
Enable Firefox with advanced tricks.

*** Options
- =enable= (boolean): Enable Firefox.
  Default: false

- =cleanHome= (boolean): Move =~/.mozilla= to =~/.local/share/mozilla=.
  Default: true

- =speechSynth= (boolean): Enable speech synthesis support.
  Default: false

** [[file:../../module/home/git.nix][git]]
Enable Git with helpful aliases and features.

*** Options
- =enable= (boolean): Enable Git configuration.

- =sshKeyFile=:
  Function to locate the SSH private key.
  #+begin_src text
    { name (string): Default file name of the SSH key (id_<name>)
    , type (string): Type prefix of the passed public key
    } -> string: Path to the SSH private key
  #+end_src

Extra packages: [[https://github.com/AGWA/git-crypt][git-crypt]], [[https://git-lfs.com/][git-lfs]], [[https://github.com/dandavison/delta][delta]]

** [[file:../../module/home/htop.nix][htop]]
Enable [[https://github.com/htop-dev/htop][htop]] with a nice default configuration

** [[file:~/dev/nix//module/home/jj/default.nix][jj]]
Enable [[https://github.com/martinvonz/jj][jujutsu]], a simple Git-compatible VCS

** [[file:../../module/home/misc.nix][misc]]
Enable miscellaneous packages and settings

** [[file:../../module/home/neofetch.nix][neofetch]]
Enable neofetch ([[https://github.com/hykilpikonna/hyfetch][hyfetch]] + [[https://github.com/fastfetch-cli/fastfetch][fastfetch]] + trans colors :3)

** [[file:../../module/home/neovim/default.nix][neovim]]
Enable [[https://github.com/neovim/neovim][neovim]] with a default configuration

** [[file:../../module/home/nix.nix][nix]]
Enable some useful aliases for nix

** [[file:../../module/home/persist.nix][persist]]
Persistent directories for this user.
List of strings (used as =d=) or entries:
- =d=: The directory to persist
- =m=: Mode of the persistent directory

*** Example
#+begin_src nix
  {
    aquaris.persist = [
      ".cache/nix"
      { d = ".gnupg"; m = "0700"; }
    ];
  }
#+end_src

** [[file:../../module/home/starship.nix][starship]]
Enable the [[https://github.com/starship/starship][starship]] shell prompt

** [[file:../../module/home/tmux/default.nix][tmux]]
Enable [[https://github.com/tmux/tmux][tmux]], a terminal multiplexer. Default prefix key: =C-w=

** [[file:../../module/home/zsh.nix][zsh]]
Enable [[https://zsh.sourceforge.io/][ZSH]] with the [[https://github.com/ohmyzsh/ohmyzsh][ohmyzsh]] configuration framework and some default configs
