* home-manager modules of Aquaris
All of these modules are rooted in =home-manager.users.<username>.aquaris=
and are enabled by default unless otherwise mentioned.

** [[file:../../module/home/bat.nix][bat]]
Enable [[https://github.com/sharkdp/bat][bat]] for manpage rendering

** [[file:../../module/home/direnv.nix][direnv]]
Enable [[https://github.com/direnv/direnv][direnv]] and [[https://github.com/nix-community/nix-direnv][nix-direnv]] integration

** [[file:../../module/home/emacs/default.nix][emacs]]
[[https://www.gnu.org/software/emacs/][Emacs]] configuration management with plugins from nixpkgs and init.org support

*** Options
- =enable= (boolean): Enable the Emacs configuration.
  Default: false

- =package=: Which Emacs package to use.
  Default: =pkgs.emacs29=

- =extraPrograms= (list of package): Extra programs available to Emacs.
  Default: empty list

- =config= (store path): Path to the config file.
  Requires file extension =.el= or =.org=

- =overrides=: Override function for emacsPackages.
  See https://mynixos.com/home-manager/option/programs.emacs.overrides.
  Default: no overrides

** [[file:../../module/home/git.nix][git]]
Enable Git with helpful aliases and features.

Extra packages: [[https://github.com/AGWA/git-crypt][git-crypt]], [[https://git-lfs.com/][git-lfs]], [[https://github.com/dandavison/delta][delta]]

** [[file:../../module/home/htop.nix][htop]]
Enable [[https://github.com/htop-dev/htop][htop]] with a nice default configuration

** [[file:../../module/home/lsd.nix][lsd]]
Enable [[https://github.com/lsd-rs/lsd][lsd]], a better ls command

** [[file:../../module/home/misc.nix][misc]]
Enable miscellaneous packages and settings

** [[file:../../module/home/neofetch.nix][neofetch]]
Enable neofetch ([[https://github.com/hykilpikonna/hyfetch][hyfetch]] + [[https://github.com/fastfetch-cli/fastfetch][fastfetch]] + trans colors :3)

** [[file:../../module/home/neovim/default.nix][neovim]]
Enable [[https://github.com/neovim/neovim][neovim]] with a default configuration

** [[file:../../module/home/persist.nix][persist]]
Persistent directories for this user.
List of strings (used as =d=) or entries:
- =d=: The directory to persist
- =m=: Mode of the persistent directory

*** Example
#+begin_src nix
  {
    aquaris.persist = [
      ".cache/nix"
      { d = ".gnupg"; m = "0700"; }
    ];
  }
#+end_src

** [[file:../../module/home/starship.nix][starship]]
Enable the [[https://github.com/starship/starship][starship]] shell prompt

** [[file:../../module/home/tmux/default.nix][tmux]]
Enable [[https://github.com/tmux/tmux][tmux]], a terminal multiplexer. Default prefix key: =C-w=
** [[file:../../module/home/zsh.nix][zsh]]
Enable [[https://zsh.sourceforge.io/][ZSH]] with the [[https://github.com/ohmyzsh/ohmyzsh][ohmyzsh]] configuration framework and some default configs
