* home-manager modules of Aquaris
All of these modules are rooted in =home-manager.users.<username>.aquaris=
and are enabled by default unless otherwise mentioned.

** [[file:../../module/home/bat.nix][bat]]
Enable [[https://github.com/sharkdp/bat][bat]] for manpage rendering

** [[file:../../module/home/direnv.nix][direnv]]
Enable [[https://github.com/direnv/direnv][direnv]] and [[https://github.com/nix-community/nix-direnv][nix-direnv]] integration

** [[file:../../module/home/emacs/default.nix][emacs]]
Declarative [[https://www.gnu.org/software/emacs/][Emacs]] configuration management

*** Options
- =enable= (boolean): Enable the Emacs configuration.
  Default: false

- =package=: Which Emacs package to use.
  Default: =pkgs.emacs29=

- =startupTimer= (boolean): Enable the startup timer.
  Default: true

- =usePackage=:
  - =alwaysDefer= (boolean): Always defer loading of packages.
    Default: false

  - =statistics= (boolean): Gather statistics about package loading times.
    Default: false

  - =verbose= (boolean): Log all loaded packages.
    Default: false

- =prelude= (string): Config to add before loading packages
  Default: empty

- =postlude= (string): Config to add after loading packages
  Default: empty

- =config=: Set of Emacs package configurations.
  Options: every keyword from [[https://github.com/jwiegley/use-package][use-package]]
  (except =disabled= and =pin=; =bind*= is set as =bind'=) and:
  - =package=: Explicit package name or function taking =epkgs=
    Default: entry name

  - =extraPackages= (list of package):
    Extra packages required by this Emacs package.
    They will be added to =home.packages=. Default: empty list

** [[file:../../module/home/eza.nix][eza]]
Enable eza, a replacement for ls

** [[file:../../module/home/firefox/default.nix][firefox]]
Enable Firefox with administrative configuration features.

*** Options
- =enable= (boolean): Enable the module

- =fork= (null, =firefox= or =librewolf=): Which fork to use
  (=null= selects vanilla Firefox). Default: =librewolf=

- =package=: The Firefox package to use. Default: =pkgs.${fork}=

- =extensions=: Attrset mapping of extension ID to options.
  You can find the ID by using [[https://github.com/mkaply/queryamoid/releases/download/v0.1/query_amo_addon_id-0.1-fx.xpi][this helper]] on the store page of any extension.
  Most likely you won't need to specify the download URL too,
  since the default chosen by this module should work just fine.

  Options:
  - =url= (string): Where to download the extension =.xpi= from.
    Default: =https://addons.mozilla.org/firefox/downloads/latest/${name}/latest.xpi=
  - =pin= (boolean): Whether to pin the extension to the navbar. Default: false
  - =private= (boolean): Whether to run this extension in private windows. Default: false

- =extraPrefs= (lines): Extra preference code; will be added to global autoconfig file

- =prefs=: Set of preferences. Values can either be:
  - null: set to default value (corresponds to =clearPref=)
  - bool, int or string: Set & lock to this value
  - An object with these options:
    - =value=: A JSON value (not just bool, int or string).
    - =locked= (bool):
      Whether to lock the pref or just set it as default
      (corresponds to =defaultPref= if false, =lockPref= if true).
      Default: true

- =policies=: Options & values according to https://mozilla.github.io/policy-templates

- =userChrome= (lines):
  Contents of userChrome.css.
  Will be copied into your profile on every launch to support sync tools.

- =captivePortal=: Support secure captive portal logins using [[https://github.com/FiloSottile/captive-browser][captive-browser]]. Options:
  - =enable= (bool): Enable this submodule (duh). Default: true
  - =url= (string): This URL will be opened in a private window to test connectivity. Default: http://neverssl.com
  - =getDNS= (string): Command that returns the fallback DNS IP.
    Default: =nmcli device show | grep IP4.DNS=
  - =port=: Port of the SOCKS5 proxy. Default: 1666

- =settings=: Various configuration templates
  - =bitwarden= (boolean): Use Bitwarden instead of the builtin password manager. Default: true
  - =harden= (boolean): Configures a bunch of security-related settings. Default: true
  - =noMozilla= (boolean): Disable Mozilla services & telemetry. Default: true
  - =qol= (boolean): Enable some quality-of-life things. Default: true
  - =ui=: Configure visibility of UI elements.
    All options are booleans and show their respective element(s) if set to =true=.
    Set =ui.invert = true= to invert this behaviour, i.e. hide on =true=.
    Available options:
    - =pagePrev=, =pageNext=: Arrow buttons that move through the current tab's history
    - =pageReload=: Tab reload & stop buttons
      (only one of them is visible at any given time; this setting hides them both)
    - =tabAll=: Little downwards-pointing triangle that shows a list of all tabs
    - =tabClose=: "×" button on each tab that closes it
    - =tabNew=: "Plus" button on the right of the tab bar that opens a new, blank tab
    - =tabPrev=, =tabNext=: Left- and rightwards-pointing triangles
      that show up when too many tabs are open to let you scroll through the tab bar
    - =toolBarSpace=: Default spacing elements on the toolbar,
      surrounding the address input
    - =windowClose=: "×" button on the very right of the tab bar that closes firefox

** [[file:../../module/home/git.nix][git]]
Enable Git with helpful aliases and features.

*** Options
- =enable= (boolean): Enable Git configuration.

- =sshKeyFile=:
  Function to locate the SSH private key.
  #+begin_src text
    { name (string): Default file name of the SSH key (id_<name>)
    , type (string): Type prefix of the passed public key
    } -> string: Path to the SSH private key
  #+end_src

Extra packages: [[https://github.com/AGWA/git-crypt][git-crypt]], [[https://git-lfs.com/][git-lfs]], [[https://github.com/dandavison/delta][delta]]

** [[file:../../module/home/htop.nix][htop]]
Enable [[https://github.com/htop-dev/htop][htop]] with a nice default configuration

** [[file:../../module/home/jj/default.nix][jj]]
Enable [[https://github.com/martinvonz/jj][jujutsu]], a simple Git-compatible VCS

** [[file:../../module/home/misc.nix][misc]]
Enable miscellaneous packages and settings

** [[file:../../module/home/neofetch.nix][neofetch]]
Enable neofetch ([[https://github.com/hykilpikonna/hyfetch][hyfetch]] + [[https://github.com/fastfetch-cli/fastfetch][fastfetch]] + trans colors :3)

** [[file:../../module/home/neovim/default.nix][neovim]]
Enable [[https://github.com/neovim/neovim][neovim]] with a default configuration

** [[file:../../module/home/nix.nix][nix]]
Enable some useful aliases for nix

** [[file:../../module/home/persist.nix][persist]]
Set of persistent directories for this user.
Name = Path of directory to be persisted (relative to $HOME).

*** Options:
- =e= (boolean): Enable this entry
- =m= (string): Mode of the persistent directory

*** Example
#+begin_src nix
  {
    aquaris.persist = {
      ".cache/nix" = { }; # all default
      ".gnupg" = { m = "0700"; };
      "foo" = { e = false; }; # disabled
    };
  }
#+end_src

** [[file:../../module/home/starship.nix][starship]]
Enable the [[https://github.com/starship/starship][starship]] shell prompt

** [[file:../../module/home/tmux/default.nix][tmux]]
Enable [[https://github.com/tmux/tmux][tmux]], a terminal multiplexer. Default prefix key: =C-w=

** [[file:../../module/home/zsh.nix][zsh]]
Enable [[https://zsh.sourceforge.io/][ZSH]] with the [[https://github.com/ohmyzsh/ohmyzsh][ohmyzsh]] configuration framework and some default configs
