* [[file:../../module/secrets.nix][aquaris.secrets]]
Powerful, built-in secrets management using [[https://github.com/42LoCo42/sillysecrets][sillysecrets]].

** Options
- =enable= (boolean): Enable the secrets management module.
  Default: true

- =pub= (string): Public key of this machine.
  If unspecified, will be read using IFD from the structure file.

- =key= (path): Path to the key for decrypting secrets.
  Default: =/var/lib/machine.key= / =/persist/var/lib/machine.key=
  if [[file:persist.org][aquaris.persist]] is enabled.

- =directory= (path):
  Secrets output directory
  (internal directory will be =.<this>.d/<sha256 of sesi.json>=).
  Default: =/run/secrets= (internally =/run/.secrets.d/<sha256>=)

- =rules= (set of submodule): Custom access rules for secrets.
  Options:
  - =user= (string): User that owns the decrypted file.
    Default: =root=, but see [[#user-secrets][User secrets]] for exceptions

  - =group= (string): Group that owns the decrypted file.
    Default: =root=

  - =mode= (string): Access mode of the decrypted file.
    Default: =0400=

- =all= (list of string; readonly):
  List of all secrets available for this machine,
  including those aliased with =@machine=.
  This is used for the checked secret accessor function.

** The machine alias
Every machine gets an alias =@machine= pointing to =machine/<name>=.
These aliases are also added to the list of all secrets.

** User secrets
While secrets are normally owned by =root=,
secrets in groups called =user/<userName>=
are considered "user secrets"
and thus owned by their respective =userName=.

*** password
The secret =user/<userName>/password=
must contain that user's password hash.

This decouples user authentication from the Nix store
and is preferred over setting =hashedPassword= directly.

NOTE: the =password= secret is owned by =root=,
despite being a user secret.
This reflects the typical behaviour of =/etc/shadow=
being readable only by =root=.

*** u2f-keys
The secret =user/<userName>/u2f-keys=
is read by =pam_u2f= (if enabled) as the =authfile= setting,
obviating the need to symlink it to =~/.config/Yubico/u2f_keys=.

*** ssh/*
All secrets below =user/<userName>/ssh/=
are used as SSH identity files when the
[[file:home/main.org#ssh][SSH module]] is enabled for that user.

** Example
Decrypted secrets of the [[file:../../example/][example]] configuration:
#+begin_src text
  /run/secrets
  ├── @machine -> machine/example
  ├── machine
  │   └── example
  │       ├── key
  │       └── something
  └── user
      └── alice
          ├── password
          └── something
#+end_src

** Usage
To convert a secret's name to its corresponding output path, call
=config.aquaris.secret= (checked) or =config.aquaris.secret'= (unchecked)
with the name.

#+begin_src nix
  { config, ... }: {
    services.vaultwarden = {
      enable = true;
      environmentFile = config.aquaris.secret "@machine/vaultwarden";
    };
  }
#+end_src
