* [[file:../../module/secrets/default.nix][aquaris.secrets]]
The set of all secrets discovered for this machine.

** Options
- =source= (path): Path of the encrypted file.
  Default: set via discovery

- =outPath= (path): Path of the decrypted file.
  Default:
  - =/run/aqs/example= for toplevel secret
  - =/run/aqs/machine/example= for machine secret
  - =/run/aqs/users/<username>/example= for user secret

- =user= (string): User that owns the decrypted file.
  Default: =root=

- =group= (string): Group that owns the decrypted file.
  Default: =root=

- =mode= (string): Access mode of the decrypted file.
  Default: =0400=

** Example
Supplied secrets:
#+begin_src text
  secrets
  ├── machines
  │   └── example
  │       └── foobar.age
  └── users
      └── alice
          └── passwordHash.age
#+end_src

Output on machine =example= where =alice= is a user:
#+begin_src text
  /run/aqs
  ├── machine
  │   └── foobar
  └── users
      └── alice
          └── passwordHash
#+end_src

** Password hashes
All user secrets named =passwordHash= are used
for the corresponding user's =hashedPasswordFile= entry.

This decouples user authentication from the Nix store
and should be preferred over setting =hashedPassword= directly.
