* [[file:../../module/secrets.nix][aquaris.secrets]]
The set of all secrets discovered for this machine.
They are managed by [[https://github.com/42LoCo42/sillysecrets][sillysecrets.]]

** Options
- =outPath= (path): Path of the decrypted file.
  Default: =/run/secrets/<groupName>/<secretName>=

- =user= (string): User that owns the decrypted file.
  Default: see [[#user-secrets][User secrets]]

- =group= (string): Group that owns the decrypted file.
  Default: =root=

- =mode= (string): Access mode of the decrypted file.
  Default: =0400=

** Aliases
Symlinks in the secrets directory.
Aliases can't have =user=, =group= or =mode= set
(instead, configure these settings on the base secret).

The following aliases are created:
- =machine/<secretName>= -> =machine:<machineName>.<secretName>=
- =user/<userName>/<secretName>= -> =user:<userName>.<secretName>=

** User secrets
While secrets are normally owned by =root=,
secrets of the form =user:<userName>.<secretName>=
are considered "user secrets"
and thus owned by their respective =userName=.

*** password
The secret =user:<userName>.password=
must contain that user's password hash.

This decouples user authentication from the Nix store
and is preferred over setting =hashedPassword= directly.

*** u2f-keys
The secret =user:<userName>.u2f-keys=
is read by =pam_u2f= (if enabled) as the =authfile= setting,
obviating the need to symlink it to =~/.config/Yubico/u2f_keys=

** Example
Decrypted secrets of the [[file:../../example/][example]] configuration:
#+begin_src text
  /run/secrets
  ├── machine
  │   └── key -> /run/secrets/machine:example/key
  ├── machine:example
  │   └── key
  ├── user
  │   └── alice
  │       └── password -> /run/secrets/user:alice/password
  └── user:alice
      └── password
#+end_src

You can use a secret like this:
#+begin_src nix
  { config, ... }: {
    services.vaultwarden = {
      enable = true;
      environmentFile = config.aquaris.secrets."machine/vaultwarden".outPath;
    };
  }
#+end_src
