** [[file:..//../../module/home/firefox/default.nix][firefox]]
Enable Firefox with administrative configuration features.

*** Options
- =enable= (boolean): Enable the module

- =fork= (null, =firefox= or =librewolf=): Which fork to use
  (=null= selects vanilla Firefox). Default: =librewolf=

- =package=: The Firefox package to use. Default: =pkgs.${fork}=

- =preRun= (lines): Shell commands to run before Firefox starts.
  Default: userChrome.css setup logic (see below)

- =postRun= (lines): Shell commands to run after Firefox has stopped.
  Default: empty

- =extensions=: Attrset mapping of extension ID to options.
  You can find the ID by using [[https://github.com/mkaply/queryamoid/releases/download/v0.1/query_amo_addon_id-0.1-fx.xpi][this helper]] on the store page of any extension.
  Most likely you won't need to specify the download URL too,
  since the default chosen by this module should work just fine.
  Options:
  - =url= (string): Where to download the extension =.xpi= from.
    Default: =https://addons.mozilla.org/firefox/downloads/latest/${name}/latest.xpi=
  - =pin= (boolean): Whether to pin the extension to the navbar. Default: false
  - =private= (boolean): Whether to run this extension in private windows. Default: false

- =extraPrefs= (lines): Extra preference code; will be added to global autoconfig file

- =prefs=: Set of preferences. Values can either be:
  - null: set to default value (corresponds to =clearPref=)
  - bool, int or string: Set & lock to this value
  - An object with these options:
    - =value=: A JSON value (not just bool, int or string).
    - =locked= (bool):
      Whether to lock the pref or just set it as default
      (corresponds to =defaultPref= if false, =lockPref= if true).
      Default: true

- =policies=: Options & values according to https://mozilla.github.io/policy-templates

- =userChrome= (lines):
  Contents of userChrome.css.
  Will be copied into your profile on every launch to support sync tools.

- =captivePortal=: Support secure captive portal logins using [[https://github.com/FiloSottile/captive-browser][captive-browser]]. Options:
  - =enable= (bool): Enable this submodule. Default: true
  - =url= (string): This URL will be opened in a private window to test connectivity. Default: http://neverssl.com
  - =getDNS= (string): Command that returns the fallback DNS IP.
    Default: =nmcli device show | grep IP4.DNS=
  - =port=: Port of the SOCKS5 proxy. Default: 1666

- =sanitize=: Delete cache & cookies when Firefox is closed. Options:
  - =enable= (bool): Enable this submodule. Default: false
  - =exceptions= (list of string): List of sites whose data will be kept. Default: empty list.
    *NOTE*: Exceptions *won't* be applied on the first run of Firefox,
    since the permissions DB doesn't exist at that point.

- =settings=: Various configuration templates
  - =bitwarden= (boolean): Use Bitwarden instead of the builtin password manager. Default: true
  - =harden= (boolean): Configures a bunch of security-related settings. Default: true
  - =noMozilla= (boolean): Disable Mozilla services & telemetry. Default: true
  - =qol= (boolean): Enable some quality-of-life things. Default: true
  - =ui=: Configure visibility of UI elements.
    All options are booleans and show their respective element(s) if set to =true=.
    Set =ui.invert = true= to invert this behaviour, i.e. hide on =true=.
    Available options:
    - =pagePrev=, =pageNext=: Arrow buttons that move through the current tab's history
    - =pageReload=: Tab reload & stop buttons
      (only one of them is visible at any given time; this setting hides them both)
    - =tabAll=: Little downwards-pointing triangle that shows a list of all tabs
    - =tabClose=: "×" button on each tab that closes it
    - =tabNew=: "Plus" button on the right of the tab bar that opens a new, blank tab
    - =tabPrev=, =tabNext=: Left- and rightwards-pointing triangles
      that show up when too many tabs are open to let you scroll through the tab bar
    - =toolBarSpace=: Default spacing elements on the toolbar,
      surrounding the address input
    - =windowClose=: "×" button on the very right of the tab bar that closes firefox
